services:
  fetcher:
    depends_on:
      - db
    image: ghcr.io/jbwittner/raidrunner_staticfetcher:develop-latest
    container_name: raidrunner_staticfetcher
    environment:
      APPLICATION_DB_HOST: db
      APPLICATION_DB_PORT: 5432
      APPLICATION_DB_NAME: raidrunner_db
      APPLICATION_DB_USER: raidrunner_user
      APPLICATION_DB_PASSWORD: RaidRunnerPass2023
      APPLICATION_BLIZZARDAPI_CLIENTID: ${RAIDRUNNER_BLIZZARD_CLIENT_ID}
      APPLICATION_BLIZZARDAPI_CLIENTSECRET: ${RAIDRUNNER_BLIZZARD_SECRET_ID}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate